pipeline {
    agent any

    stages {
        stage('Build Jar') {
            agent {
                docker {
                    image 'maven:3.9.3-eclipse-temurin-17-focal'
                    args '-u root -v /tmp/m2:/root/.m2'
                }
            }
            steps {
                bat 'mvn clean package -DskipTests'
            }
        }

        stage('Build Image') {
            steps {
                script {
                    app = docker.build('yehorychev/selenium-docker')
                }
            }
        }

        stage('Push Image') {
            environment {
                DOCKER_HUB = credentials('docker-hub-credentials')
            }
            steps {
                script {
                    docker.withRegistry('', 'docker-hub-credentials') {
                        app.push("latest")
                    }
                }
            }
        }
    }

    post {
        always {
            bat 'docker logout'
        }
    }
}